[[Liburing]]
arch = "aarch64"
git-tree-sha1 = "4d38e2a728a47853333a27ecc74b5b6cb7dd773f"
libc = "glibc"
os = "linux"

    [[Liburing.download]]
    sha256 = "cacbfda2baf312d79931333e20434e3710ef79e03db762dcae81b46aaab41829"
    url = "https://github.com/JuliaBinaryWrappers/Liburing_jll.jl/releases/download/Liburing-v2.12.0+0/Liburing.v2.12.0.aarch64-linux-gnu.tar.gz"
[[Liburing]]
arch = "aarch64"
git-tree-sha1 = "04b858809c470edba0d46e4775786e3d69c0419b"
libc = "musl"
os = "linux"

    [[Liburing.download]]
    sha256 = "950d6cd56e43a8cea4c222a6791946f16219b6089c74ee874ce77fbf93ea6a20"
    url = "https://github.com/JuliaBinaryWrappers/Liburing_jll.jl/releases/download/Liburing-v2.12.0+0/Liburing.v2.12.0.aarch64-linux-musl.tar.gz"
[[Liburing]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "adfea4d3acf7ab625f103e2536c18e8113a4d922"
libc = "glibc"
os = "linux"

    [[Liburing.download]]
    sha256 = "32fab97fcad0cdee2246df401f0155a1b174878952d3be4df5e4efcf687215f8"
    url = "https://github.com/JuliaBinaryWrappers/Liburing_jll.jl/releases/download/Liburing-v2.12.0+0/Liburing.v2.12.0.armv6l-linux-gnueabihf.tar.gz"
[[Liburing]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d813dd624297d316e8cf6cba5c07aa2c5c6a7ce8"
libc = "musl"
os = "linux"

    [[Liburing.download]]
    sha256 = "7883d47fef9a3de91e360ee42bc50dc63cb0f774312a09bad269ccf8f4f92ed4"
    url = "https://github.com/JuliaBinaryWrappers/Liburing_jll.jl/releases/download/Liburing-v2.12.0+0/Liburing.v2.12.0.armv6l-linux-musleabihf.tar.gz"
[[Liburing]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "43326b0cfd307dcab7d1f5928ecd79a1688c2ade"
libc = "glibc"
os = "linux"

    [[Liburing.download]]
    sha256 = "0ade420f79b41d20a5a8861b876ac120e0ecae07f9fccc52804ada11f636a966"
    url = "https://github.com/JuliaBinaryWrappers/Liburing_jll.jl/releases/download/Liburing-v2.12.0+0/Liburing.v2.12.0.armv7l-linux-gnueabihf.tar.gz"
[[Liburing]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "25e5a002b3cbc66498ade038f5c4c93c66c9f6ba"
libc = "musl"
os = "linux"

    [[Liburing.download]]
    sha256 = "7e70bf8baaef4ddb69c26cadd80c2208dfbc674b92402bc166dfe77fb17f4e9b"
    url = "https://github.com/JuliaBinaryWrappers/Liburing_jll.jl/releases/download/Liburing-v2.12.0+0/Liburing.v2.12.0.armv7l-linux-musleabihf.tar.gz"
[[Liburing]]
arch = "i686"
git-tree-sha1 = "69cb261da3f0c8b9db6b56f93eb2b4b0578ea584"
libc = "glibc"
os = "linux"

    [[Liburing.download]]
    sha256 = "93436dd77d074deac8b9858555e5628bf185bf1d9f82baeb2ca0ec8dde9ec931"
    url = "https://github.com/JuliaBinaryWrappers/Liburing_jll.jl/releases/download/Liburing-v2.12.0+0/Liburing.v2.12.0.i686-linux-gnu.tar.gz"
[[Liburing]]
arch = "i686"
git-tree-sha1 = "eaa1678fa0c319770810a942d923105b2194685c"
libc = "musl"
os = "linux"

    [[Liburing.download]]
    sha256 = "ac560b1f542d6dcff9f45c1d7c63f8e6fbee8fc626e4427753e0acea735a0dd3"
    url = "https://github.com/JuliaBinaryWrappers/Liburing_jll.jl/releases/download/Liburing-v2.12.0+0/Liburing.v2.12.0.i686-linux-musl.tar.gz"
[[Liburing]]
arch = "powerpc64le"
git-tree-sha1 = "361fb05d56bb759a1d4a0c936a6a828870d1341d"
libc = "glibc"
os = "linux"

    [[Liburing.download]]
    sha256 = "0b932e17a26a795d5e1df0064a0c34d4b4d7030640389634f4eea043cd5c7650"
    url = "https://github.com/JuliaBinaryWrappers/Liburing_jll.jl/releases/download/Liburing-v2.12.0+0/Liburing.v2.12.0.powerpc64le-linux-gnu.tar.gz"
[[Liburing]]
arch = "riscv64"
git-tree-sha1 = "e802fe4fee949a0c1ec57c924c285cd8631cd1cd"
libc = "glibc"
os = "linux"

    [[Liburing.download]]
    sha256 = "d9449e9da2e1408dd1364c8031cc6256c1c57426c93a378323758ffe1dc9983a"
    url = "https://github.com/JuliaBinaryWrappers/Liburing_jll.jl/releases/download/Liburing-v2.12.0+0/Liburing.v2.12.0.riscv64-linux-gnu.tar.gz"
[[Liburing]]
arch = "x86_64"
git-tree-sha1 = "bd4d32f31978b02ce7b42dc3a44aa7c5c984d398"
libc = "glibc"
os = "linux"

    [[Liburing.download]]
    sha256 = "fc098e41d13d836f3439fdf26953d33de3158e70499577a93109eb72b4ba0398"
    url = "https://github.com/JuliaBinaryWrappers/Liburing_jll.jl/releases/download/Liburing-v2.12.0+0/Liburing.v2.12.0.x86_64-linux-gnu.tar.gz"
[[Liburing]]
arch = "x86_64"
git-tree-sha1 = "5e9df7915f9d5136ae4a3f6a1c48399946fa30cf"
libc = "musl"
os = "linux"

    [[Liburing.download]]
    sha256 = "ec0e4cf3570301cc59dd3d5938ddae101c0666cd863966eba37750f100b796f0"
    url = "https://github.com/JuliaBinaryWrappers/Liburing_jll.jl/releases/download/Liburing-v2.12.0+0/Liburing.v2.12.0.x86_64-linux-musl.tar.gz"
